---
- name: Install the tcp_server daemon systemd script
  template:
    src: tcp_test_server.service
    dest: /etc/systemd/system/tcp_test_server.service
    mode: 0644

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the tcp_test_server service is stopped
  systemd:
    name: tcp_test_server
    daemon_reload: yes
    enabled: no
    state: stopped