---
- set_fact: version="{{ version_with_hash.split("-")[0] }}"

- name: Setup the splunk user
  user:
    name: splunk
    createhome: no
    home: /opt/splunk
    shell: /usr/sbin/nologin

- name: "Downloading Splunk Heavy Forwarder ({{ version }})"
  get_url:
    url: "https://download.splunk.com/products/splunk/releases/{{ version }}/linux/splunk-{{ version_with_hash }}-linux-2.6-amd64.deb"
    dest: /tmp/splunk_heavy_forwarder.deb
    mode: 0644

- name: Install the Splunk Heavy Forwarder
  shell: dpkg -i /tmp/splunk_heavy_forwarder.deb

- name: Remove Splunk Heavy Forwarder archive
  file:
    path: /tmp/splunk_heavy_forwarder.tar.gz
    state: absent

- name: Install splunk_heavy_forwarder daemon systemd script
  copy:
    src: splunk_heavy_forwarder.service
    dest: /etc/systemd/system/splunk_heavy_forwarder.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the splunk_heavy_forwarder service is stopped
  systemd:
    name: splunk_heavy_forwarder
    daemon_reload: yes
    enabled: no
    state: stopped