---
- name: create directory for ansible custom facts
  file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d

- name: install subject facts
  copy:
    src: subjects.fact
    dest: /etc/ansible/facts.d

- name: re-read facts after adding custom fact
  setup:
    filter: ansible_local
