---
- name: Update apt
  apt:
    update_cache: true

# zsh is a shell environment; we install it for the few times we
# need to SSH the instance (David and Ben prefer zsh over bash)
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Configure default .zshrc
  copy:
    src: /etc/zsh/newuser.zshrc.recommended
    dest: /etc/skel/.zshrc
    remote_src: yes

# curl is a HTTP request tool; it is used for downloading files to
# the instance; it is typically easier to use than wget
- name: Install curl
  apt:
    name: curl
    state: present

# htop is a better version of top; we install it for the few times
# we SSH into the instance and need to view resource usage
- name: Install htop
  apt:
    name: htop
    state: present

# jq is a utility for manipulating JSON; we use it when parsing
# data payloads from AWS when initializing
- name: Install jq
  apt:
    name: jq
    state: present

# socat is a utility for talking directly to sockets.
# This is useful, e.g., when interacting with the HAProxy stats socket.
- name: Install socat
  apt:
    name: socat
    state: present

# tree is a utility for showing a directory structure as a tree;
# it's useful when trying to understand the locations of files
# in a directory
- name: Install tree
  apt:
    name: tree
    state: present
