---
- name: Setup the sumocollector user
  user:
    name: sumocollector
    createhome: no
    home: /opt/sumocollector
    shell: /usr/sbin/nologin

- name: Create the /etc/sumocollector directory
  file:
    path: /etc/sumocollector
    state: directory

- name: Install SumoCollector configuration
  template:
    src: "{{ configuration_file }}"
    dest: /etc/sumocollector/sumocollector.toml
    mode: 0644

- name: "Downloading SumoCollector ({{ version }})"
  get_url:
    url: https://collectors.au.sumologic.com/rest/download/deb/64
    dest: /tmp/sumocollector.deb
    mode: 0644

- name: Install SumoCollector
  shell: dpkg -i /tmp/sumocollector.deb

- name: Remove SumoCollector archive
  file:
    path: /tmp/sumocollector.deb
    state: absent

- name: Put config file in place
  template:
    src: 'templates/user.properties.j2'
    dest: '/opt/sumocollector/config/user.properties'
    owner: root
    group: sumocollector
  become: yes  

- name: Put sources file in place
  template:
    src: 'templates/sources.json.j2'
    dest: '/opt/sumocollector/config/sources.json'
    owner: root
    group: sumocollector
  become: yes  

- name: Install sumocollector daemon systemd script
  copy:
    src: sumocollector.service
    dest: /etc/systemd/system/sumocollector.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the sumocollector service is stopped
  systemd:
    name: sumocollector
    daemon_reload: yes
    enabled: no
    state: stopped