---
- set_fact: version="{{ version_with_hash.split("-")[0] }}"

- name: Setup the splunk user
  user:
    name: splunk
    createhome: no
    home: /opt/splunk
    shell: /usr/sbin/nologin

- name: "Downloading Splunk Universal Forwarder ({{ version }})"
  get_url:
    url: "https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version={{ version }}&product=universalforwarder&filename=splunkforwarder-{{ version_with_hash }}-linux-2.6-amd64.deb&wget=true"
    dest: /tmp/splunk_universal_forwarder.deb
    mode: 0644

- name: Install the Splunk Universal Forwarder
  shell: dpkg -i /tmp/splunk_universal_forwarder.deb

- name: Remove Splunk Universal Forwarder archive
  file:
    path: /tmp/splunk_universal_forwarder.deb
    state: absent

- name: Install Splunk Universal Forwarder limits configuration
  copy:
    src: limits.conf
    dest: /opt/splunkforwarder/etc/apps/SplunkUniversalForwarder/default/limits.conf
    mode: 0644

- name: Install splunk_universal_forwarder daemon systemd script
  copy:
    src: splunk_universal_forwarder.service
    dest: /etc/systemd/system/splunk_universal_forwarder.service
    mode: 0644
    remote_src: no

# This ensures that the process is not running. Each test is responsible
# for starting and stopping the relevant services.
- name: Ensure the splunk_universal_forwarder service is stopped
  systemd:
    name: splunk_universal_forwarder
    daemon_reload: yes
    enabled: no
    state: stopped