---
- name: Remove previous test log file
  file:
    path: "{{ location }}"
    state: absent

- name: Create 100MiB test JSON log file
  when: encoding is "json"
  shell: |
    flog --format {{ format }} --bytes {{ bytes }} | \
      jq -c --raw-input '{msg: .}' \
      > {{ location }}

- name: Create 100MiB test text log file
  when: encoding is "text"
  shell: |
    flog --format {{ format }} --bytes {{ bytes }} > {{ location }}
