---
- name: "Sending data to {{ address }} for {{ timeout }} seconds"
  command:
    argv: [
      "socat_loop",
      timeout,
      file,
      "-u",
      "-",
      address
    ]
  register: socat_loop
  failed_when: socat_loop.rc != 124
