logging.level: info

filebeat.inputs:
- type: log
  enabled: true
  scan_frequency: 2
  tail_files: false
  paths:
    - {{ test_file_location }}

output.logstash:
  hosts: ["127.0.0.1:{{ tcp_consumer_port }}"]

# output.elasticsearch:
#   hosts: ["localhost:{{ http_consumer_port }}"]
#   protocol: http
#   path: /elasticsearch