---
- hosts: default
  become: true
  roles:
    - no_auto_update
    - utilities
    - python3
    - awscli
    - journald-rate-limits
    - flog

    - role: socat_loop
      action: install

    - role: file_test_server
      action: install

    - role: http_test_server
      action: install

    - role: profiling
      action: install

    - role: docker
      action: install

    - role: python-docker
      action: install

    - role: subjects
      action: install

    - role: tcp_test_server
      action: install
