---
- name: Install Logstash settings configuration
  template:
    src: "{{ configuration_file }}"
    dest: /etc/logstash/logstash.yml
    mode: 0644
  when: configuration_file != ""

- name: Install Logstash pipeline configuration
  template:
    src: "{{ pipeline_file }}"
    dest: /etc/logstash/conf.d/logstash.conf
    mode: 0644