[sources.in]
  type               = "file"
  include            = ["{{ test_file_location }}"]
  start_at_beginning = true

[sinks.out]
  inputs  = ["in"]
  type    = "tcp"
  address = "127.0.0.1:{{ tcp_consumer_port }}"
