data_dir = "/var/lib/vector"

[sources.in]
  type    = "socket"
  mode    = "tcp"
  address = "0.0.0.0:{{ subject_port }}"

[sinks.out]
  inputs  = ["in"]
  type    = "socket"
  mode    = "tcp"
  address = "{{ consumer_ip }}:{{ consumer_port }}"

  [sinks.out.buffer]
    type      = "disk"
    max_size  = 104857600 # 100MiB
    when_full = "block"
