---
- import_playbook: reset.yml

- hosts: '{{ test_namespace }}'
  become: true
  tasks:
    - set_fact:
        consumer_instance: "{{ hostvars[groups['tag_Name_vector_test_' + user_id + '_' + test_name + '_' + test_configuration + '_consumer'].0] }}"
        consumer_role: "{% if test_subject=='filebeat' %}logstash{% else %}tcp_test_server{% endif %}"

- hosts: '{{ test_namespace }}:&tag_TestRole_consumer'
  become: true
  tasks:
    - include_role:
        name: "{{ consumer_role }}"
      vars:
        action: start

- hosts: '{{ test_namespace }}:&tag_TestRole_subject'
  become: true
  tasks:
    - name: Wait for port {{ consumer_instance.ec2_private_ip_address }}:{{ consumer_port }} to become available
      wait_for:
        host: "{{ consumer_instance.ec2_private_ip_address }}"
        port: "{{ consumer_port }}"
        delay: 1

    - name: Start {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: start

    - name: Wait 15 seconds for {{ test_subject }} to initialize and warmup
      pause:
        seconds: 15

    - name: Start profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: start

    - name: Wait 60 seconds for {{ test_subject }} to run
      pause:
        seconds: 60

    - name: Stop profiling {{ test_subject }}
      include_role:
        name: profiling
      vars:
        action: stop

    - name: Stop {{ test_subject }}
      include_role:
        name: "{{ test_subject }}"
      vars:
        action: stop

- hosts: '{{ test_namespace }}:&tag_TestRole_consumer'
  become: true
  tasks:
    - include_role:
        name: "{{ consumer_role }}"
      vars:
        action: stop